
spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_router?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: hsp
  # Session 配置
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000
  # Redis 配置
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

# MyBatis Flex 配置
mybatis-flex:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
