
spring:
  application:
    name: ai-router
  profiles:
    active: local
  ai:
     openai:
       # 通义千问兼容 OpenAI 接口
       base-url: https://dashscope.aliyuncs.com/compatible-mode
       api-key: ${QWEN_API_KEY:YOUR_QWEN_API_KEY}
       chat:
         options:
           model: qwen-plus
           temperature: 0.7

server:
  port: 8127
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.yzj.airouter.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn


